// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_SCREEN3_H
#define _UI_SCREEN3_H

#ifdef __cplusplus
  extern "C" {
#endif

#include "lvgl.h"
#include <stdint.h>

///////////////////// VARIABLES ////////////////////
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_LabelTitle3;
extern lv_obj_t *ui_LabelMAVLink;
extern lv_obj_t *ui_LabelSerialInfo;
extern lv_obj_t *ui_LabelBatteryInfo;
extern lv_obj_t *ui_LabelStatus;

///////////////////// FUNCTION PROTOTYPES ////////////////////
void ui_Screen3_screen_init(void);
void ui_Screen3_screen_destroy(void);
void update_reboot_button_visibility(void);
// GPS update function for Screen3
void update_screen3_gps(int32_t lat, int32_t lon, int32_t alt, uint8_t satellites, uint8_t fix_type);

// Raw serial data functions
void ui_add_raw_serial_byte(uint8_t byte);
void ui_update_raw_serial_display(void);
void ui_clear_raw_serial_buffer(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
