// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_event_Screen2( lv_event_t * e);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_Colorwheel1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
// GPS sub-screen objects
extern lv_obj_t *ui_Screen2_GPS_Panel;
extern lv_obj_t *ui_Screen2_GPS_Lat;
extern lv_obj_t *ui_Screen2_GPS_Lon;
extern lv_obj_t *ui_Screen2_GPS_Alt;
extern lv_obj_t *ui_Screen2_GPS_Sats;
extern lv_obj_t *ui_Screen2_GPS_Fix;
extern lv_obj_t *ui_Screen2_ToggleBtn;
// Function to update GPS display
void update_screen2_gps(int32_t lat, int32_t lon, int32_t alt, uint8_t satellites, uint8_t fix_type);
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

