// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_SCREEN3_H
#define _UI_SCREEN3_H

#ifdef __cplusplus
  extern "C" {
#endif

#include "lvgl.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_LabelTitle3;
lv_obj_t *ui_LabelMAVLink;
lv_obj_t *ui_LabelSerialInfo;
lv_obj_t *ui_LabelBatteryInfo;
lv_obj_t *ui_LabelStatus;

///////////////////// FUNCTION PROTOTYPES ////////////////////
void ui_Screen3_screen_init(void);
void ui_Screen3_screen_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
