// This file was generated by SquareLine Studio
// Refactored for clean modal buttons

#include <stdio.h>
#include <string.h>
#include <Arduino.h>
#include <MAVLink.h>
#include "../ui.h"
#include "ui_Screen3.h"

// External MAVLink data from main.cpp
extern struct MAVLinkData {
    float voltage;
    float current;
    uint8_t percent;
    unsigned long last_update;
    bool data_valid;
    unsigned long last_heartbeat;
    bool heartbeat_received;
    // Extended battery info
    int16_t temperature;        // Temperature in 0.01 degrees C
    int32_t time_remaining;     // Seconds
    uint8_t charge_state;       // Charge state
    uint16_t cell_voltages[6];  // First 6 cell voltages in mV
    uint8_t cell_count;         // Number of cells detected
    // Heartbeat info (from actual MAVLink messages)
    uint8_t autopilot_type;     // MAV_AUTOPILOT enum (e.g., 12=PX4, 3=ArduPilot)
    uint8_t system_type;        // MAV_TYPE enum (e.g., 2=QUADROTOR)
    uint8_t base_mode;          // System mode
    uint8_t system_status;      // System status
    uint32_t heartbeat_count;   // Total heartbeats received
    // Autopilot version info
    uint32_t flight_sw_version; // Flight software version
    uint32_t board_version;     // Board version
    uint16_t vendor_id;         // Vendor ID
    uint16_t product_id;        // Product ID
    bool version_received;      // Flag if version info was received
    // CPU Temperatures
    float esp32_temperature;    // ESP32 internal temp in Celsius
    float mavlink_cpu_temp;     // MAVLink autopilot CPU temp in Celsius (if available)
    // SYS_STATUS (ID 1)
    uint16_t load;              // Maximum usage in percent of mainloop time
    uint16_t voltage_battery;   // Battery voltage in mV
    int16_t current_battery;    // Battery current in 10mA
    uint16_t drop_rate_comm;    // Communication drop rate in 10000ths of percent
    uint16_t errors_comm;       // Communication errors
    // SCALED_PRESSURE (ID 29)
    float temperature_press;    // Scaled pressure temperature in Celsius
    float press_abs;            // Absolute pressure in hPa
    float press_diff;           // Differential pressure in hPa
    // SYSTEM_TIME (ID 2)
    uint64_t time_unix_usec;    // Unix time in microseconds
    // IMU (SCALED_IMU2, ID 116)
    float temperature_imu;      // IMU temperature in Celsius
} mavlink_data;

// Helper function to get autopilot name from MAV_AUTOPILOT enum
static const char* get_autopilot_name(uint8_t autopilot) {
    switch (autopilot) {
        case 0: return "Generic";
        case 1: return "Reserved";
        case 2: return "SLUGS";
        case 3: return "ArduPilot";
        case 4: return "OpenPilot";
        case 5: return "Generic_W";
        case 6: return "PPZ";
        case 7: return "UDB";
        case 8: return "FlexiPilot";
        case 10: return "SMACCMPilot";
        case 11: return "AutoQuad";
        case 12: return "PX4";
        case 13: return "SMAVLink";
        case 14: return "SmartAP";
        case 15: return "Airware";
        case 16: return "Path_Pilot";
        default: return "Unknown";
    }
}

// Helper function to get system type name from MAV_TYPE enum
static const char* get_system_type_name(uint8_t type) {
    switch (type) {
        case 0: return "Generic";
        case 1: return "Fixed Wing";
        case 2: return "Quadrotor";
        case 3: return "Coaxial";
        case 4: return "Helicopter";
        case 5: return "Antenna Tracker";
        case 6: return "GCS";
        case 13: return "Hexarotor";
        case 14: return "Octorotor";
        case 15: return "Tricopter";
        case 20: return "VTOL";
        case 27: return "Rover";
        case 28: return "Boat";
        case 30: return "Submarine";
        default: return "Unknown";
    }
}
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_LabelTitle3;
lv_obj_t *ui_LabelMAVLink = NULL;
lv_obj_t *ui_LabelBatteryInfo = NULL;
lv_obj_t *ui_LabelStatus = NULL;
static lv_obj_t *ui_RebootButton = NULL;

// GPS objects for Screen3
lv_obj_t *ui_Screen3_GPS_Panel = NULL;
lv_obj_t *ui_Screen3_GPS_Lat = NULL;
lv_obj_t *ui_Screen3_GPS_Lon = NULL;
lv_obj_t *ui_Screen3_GPS_Alt = NULL;
lv_obj_t *ui_Screen3_GPS_Sats = NULL;
lv_obj_t *ui_Screen3_GPS_Fix = NULL;
lv_obj_t *ui_Screen3_ToggleBtn = NULL;
static bool ui_Screen3_GPS_Mode = false;  // false = Menu, true = GPS

// Navigation to Screen4
extern lv_obj_t *ui_Screen2;
extern void ui_Screen2_screen_init(void);
extern lv_obj_t *ui_Screen4;
extern void ui_Screen4_screen_init(void);

///////////////////// FORWARD DECLARATIONS ////////////////////
static void modal_close_cb(lv_event_t *e);
static lv_obj_t* create_detail_modal(const char *title, const char *content);
static lv_obj_t* create_menu_button(lv_obj_t *parent, const char *label_text, lv_event_cb_t click_cb, lv_color_t text_color, lv_coord_t y_pos);
void update_reboot_button_visibility(void);
static void mavlink_btn_click_cb(lv_event_t *e);
static void battery_btn_click_cb(lv_event_t *e);
static void system_btn_click_cb(lv_event_t *e);
static void reboot_btn_click_cb(lv_event_t *e);
static void ui_event_Screen3(lv_event_t *e);
static void ui_enable_event_bubble_recursive(lv_obj_t *parent);

// Swipe detection state
static lv_point_t ui_Screen3_press_point;
static bool ui_Screen3_press_active = false;
static uint32_t ui_Screen3_load_time = 0;

///////////////////// MODAL FUNCTIONS ////////////////////

static void modal_close_cb(lv_event_t *e) {
    lv_obj_t *modal = lv_event_get_current_target(e);
    lv_obj_del(modal);
}

static lv_obj_t* create_detail_modal(const char *title, const char *content) {
    lv_obj_t *modal = lv_obj_create(lv_scr_act());
    lv_obj_set_size(modal, 200, 180);
    lv_obj_center(modal);
    lv_obj_set_style_bg_color(modal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(modal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(modal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(modal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_t *title_label = lv_label_create(modal);
    lv_obj_set_style_text_font(title_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(title_label, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(title_label, title);
    lv_obj_align(title_label, LV_ALIGN_TOP_MID, 0, 10);
    
    lv_obj_t *content_label = lv_label_create(modal);
    lv_obj_set_style_text_font(content_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(content_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(content_label, content);
    lv_obj_align(content_label, LV_ALIGN_TOP_LEFT, 10, 35);
    lv_label_set_long_mode(content_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(content_label, 180);
    
    lv_obj_add_flag(modal, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(modal, modal_close_cb, LV_EVENT_CLICKED, NULL);
    
    lv_obj_clear_flag(title_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(content_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(title_label, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_flag(content_label, LV_OBJ_FLAG_EVENT_BUBBLE);
    
    return modal;
}



///////////////////// BUTTON HANDLERS ////////////////////

static void mavlink_btn_click_cb(lv_event_t *e) {
    (void)e;
    char mavlink_text[300];
    
    if (mavlink_data.heartbeat_received) {
        if (mavlink_data.version_received) {
            sprintf(mavlink_text,
                "Status: %s\n"
                "Heartbeats: %u\n"
                "Battery: %.1fV %.1fA %d%%\n"
                "Connection: %s\n"
                "System: %s\n"
                "Type: %s\n"
                "FW: %08X | Board: %08X\n"
                "Vendor: %04X | Product: %04X\n"
                "MAVLink: v2.0\n"
                "CPU: %.1f°C | Errors: %u",
                mavlink_data.data_valid ? "Receiving" : "Waiting",
                (unsigned int)mavlink_data.heartbeat_count,
                mavlink_data.voltage, mavlink_data.current, mavlink_data.percent,
                mavlink_data.data_valid ? "OK" : "Waiting",
                get_autopilot_name(mavlink_data.autopilot_type),
                get_system_type_name(mavlink_data.system_type),
                mavlink_data.flight_sw_version,
                mavlink_data.board_version,
                mavlink_data.vendor_id,
                mavlink_data.product_id,
                mavlink_data.esp32_temperature,
                mavlink_data.errors_comm);
        } else {
            sprintf(mavlink_text,
                "Status: %s\n"
                "Heartbeats: %u\n"
                "Battery: %.1fV %.1fA %d%%\n"
                "Connection: %s\n"
                "System: %s\n"
                "Type: %s\n"
                "FW: Requesting...\n"
                "MAVLink: v2.0\n"
                "CPU: %.1f°C | Errors: %u",
                mavlink_data.data_valid ? "Receiving" : "Waiting",
                (unsigned int)mavlink_data.heartbeat_count,
                mavlink_data.voltage, mavlink_data.current, mavlink_data.percent,
                mavlink_data.data_valid ? "OK" : "Waiting",
                get_autopilot_name(mavlink_data.autopilot_type),
                get_system_type_name(mavlink_data.system_type),
                mavlink_data.esp32_temperature,
                mavlink_data.errors_comm);
        }
    } else {
        sprintf(mavlink_text,
            "Status: Waiting...\n"
            "Heartbeats: 0\n"
            "Battery: --\n"
            "Connection: --\n"
            "System: --\n"
            "Type: --\n"
            "MAVLink: v2.0\n"
            "\nCheck cable D2 (RX)");
    }
    
    create_detail_modal("MAVLink Details", mavlink_text);
}


static void battery_btn_click_cb(lv_event_t *e) {
    (void)e;
    char battery_text[300];
    
    if (mavlink_data.data_valid) {
        // Calculate flight time from time_remaining
        int hours = mavlink_data.time_remaining / 3600;
        int mins = (mavlink_data.time_remaining % 3600) / 60;
        
        // Build cell voltages string
        char cells_str[100] = "";
        for (int i = 0; i < mavlink_data.cell_count && i < 6; i++) {
            char cell[20];
            sprintf(cell, "C%d:%.2fV ", i+1, mavlink_data.cell_voltages[i] / 1000.0);
            strcat(cells_str, cell);
        }
        
        // Build temperature string
        char temp_str[20];
        if (mavlink_data.temperature == 0) {
            strcpy(temp_str, "--");
        } else {
            sprintf(temp_str, "%.1fC", mavlink_data.temperature / 100.0);
        }
        
        sprintf(battery_text,
            "Battery: %s\n"
            "Voltage: %.2fV (%dS)\n"
            "Current: %.2fA\n"
            "Remaining: %d%%\n"
            "Flight Time: %02d:%02d\n"
            "Temp: %s\n"
            "Cells: %s",
            mavlink_data.percent > 20 ? "OK" : "LOW",
            mavlink_data.voltage,
            mavlink_data.cell_count,
            mavlink_data.current,
            mavlink_data.percent,
            hours, mins,
            temp_str,
            cells_str[0] ? cells_str : "N/A");
    } else {
        sprintf(battery_text,
            "Battery: --\n"
            "Voltage: --\n"
            "Current: --\n"
            "Remaining: --\n"
            "Flight Time: --\n"
            "Temp: --\n"
            "Waiting for MAVLink data...");
    }
    
    create_detail_modal("Battery Details", battery_text);
}

static void system_btn_click_cb(lv_event_t *e) {
    (void)e;
    char system_text[400];
    
    // Get uptime in seconds
    unsigned long uptime_s = millis() / 1000;
    int up_h = uptime_s / 3600;
    int up_m = (uptime_s % 3600) / 60;
    int up_s = uptime_s % 60;
    
    // Build temperature strings for MAVLink sensors
    char imu_temp_str[20] = "--";
    char press_temp_str[20] = "--";
    if (mavlink_data.temperature_imu != 0) {
        sprintf(imu_temp_str, "%.1fC", mavlink_data.temperature_imu / 100.0);
    }
    if (mavlink_data.temperature_press != 0) {
        sprintf(press_temp_str, "%.1fC", mavlink_data.temperature_press / 100.0);
    }
    
    sprintf(system_text,
        "Disp.Temp: %.1fC\n"
        "IMU Temp: %s\n"
        "Press Temp: %s\n"
        "CPU Load: %d%%\n"
        "Errors: %d\n"
        "Uptime: %02d:%02d:%02d\n"
        "Ver: v.0.1",
        mavlink_data.esp32_temperature,
        imu_temp_str,
        press_temp_str,
        mavlink_data.load,
        mavlink_data.errors_comm,
        up_h, up_m, up_s);
    
    create_detail_modal("System Status", system_text);
}

// External wrapper function from main.cpp
extern void send_mavlink_reboot(void);

static void reboot_btn_click_cb(lv_event_t *e) {
    (void)e;
    
    send_mavlink_reboot();
    create_detail_modal("Reboot", "Reboot command sent!\n\nFlight controller\nwill restart.");
}

///////////////////// BUTTON CREATOR ////////////////////

static lv_obj_t* create_menu_button(lv_obj_t *parent, const char *label_text, lv_event_cb_t click_cb, lv_color_t text_color, lv_coord_t y_pos) {
    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_set_size(btn, 180, 40);
    lv_obj_align(btn, LV_ALIGN_TOP_LEFT, 5, y_pos);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x2a2a2a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x3a3a3a), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(btn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(btn, click_cb, LV_EVENT_CLICKED, NULL);
    
    lv_obj_t *label = lv_label_create(btn);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(label, label_text);
    lv_obj_center(label);
    
    return btn;
}

///////////////////// SCREEN INITIALIZATION ////////////////////

// Toggle between Menu and GPS display on Screen3
static void ui_Screen3_switch_mode(bool gps_mode) {
    ui_Screen3_GPS_Mode = gps_mode;
    if (gps_mode) {
        // Show GPS panel, hide menu panel
        if (ui_Panel3) lv_obj_add_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);
        if (ui_Screen3_GPS_Panel) lv_obj_clear_flag(ui_Screen3_GPS_Panel, LV_OBJ_FLAG_HIDDEN);
        if (ui_Screen3_ToggleBtn) lv_label_set_text(lv_obj_get_child(ui_Screen3_ToggleBtn, 0), "MENU");
    } else {
        // Show menu, hide GPS
        if (ui_Panel3) lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_HIDDEN);
        if (ui_Screen3_GPS_Panel) lv_obj_add_flag(ui_Screen3_GPS_Panel, LV_OBJ_FLAG_HIDDEN);
        if (ui_Screen3_ToggleBtn) lv_label_set_text(lv_obj_get_child(ui_Screen3_ToggleBtn, 0), "GPS");
    }
}

// Toggle button callback
static void ui_Screen3_toggle_cb(lv_event_t *e) {
    (void)e;
    ui_Screen3_switch_mode(!ui_Screen3_GPS_Mode);
}

// GPS panel click callback - close when clicked
static void ui_Screen3_gps_panel_click_cb(lv_event_t *e) {
    (void)e;
    // Close GPS panel and return to menu
    ui_Screen3_switch_mode(false);
}

// Update GPS display on Screen3
void update_screen3_gps(int32_t lat, int32_t lon, int32_t alt, uint8_t satellites, uint8_t fix_type) {
    // Only update if GPS panel exists
    if (!ui_Screen3_GPS_Lat || !ui_Screen3_GPS_Lon || !ui_Screen3_GPS_Alt) return;
    
    char buf[32];
    
    // Format latitude (degrees * 1e7)
    float lat_deg = lat / 1e7f;
    sprintf(buf, "Lat: %.6f", lat_deg);
    lv_label_set_text(ui_Screen3_GPS_Lat, buf);
    
    // Format longitude (degrees * 1e7)
    float lon_deg = lon / 1e7f;
    sprintf(buf, "Lon: %.6f", lon_deg);
    lv_label_set_text(ui_Screen3_GPS_Lon, buf);
    
    // Format altitude (mm to m)
    int alt_m = alt / 1000;
    sprintf(buf, "Alt: %d m", alt_m);
    lv_label_set_text(ui_Screen3_GPS_Alt, buf);
    
    // Satellites
    sprintf(buf, "Sats: %d", satellites);
    lv_label_set_text(ui_Screen3_GPS_Sats, buf);
    
    // Fix type with color coding
    const char* fix_str;
    lv_color_t fix_color;
    switch (fix_type) {
        case 0:
        case 1:
            fix_str = "No GPS";
            fix_color = lv_color_hex(0xFF0000);  // Red
            break;
        case 2:
            fix_str = "2D Fix";
            fix_color = lv_color_hex(0xFFFF00);  // Yellow
            break;
        case 3:
            fix_str = "3D Fix";
            fix_color = lv_color_hex(0x00FF00);  // Green
            break;
        default:
            fix_str = "Unknown";
            fix_color = lv_color_hex(0x808080);  // Gray
    }
    lv_label_set_text(ui_Screen3_GPS_Fix, fix_str);
    lv_obj_set_style_text_color(ui_Screen3_GPS_Fix, fix_color, LV_PART_MAIN);
}

void ui_Screen3_screen_init(void) {
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen3, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Screen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Create main panel - transparent background
    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_size(ui_Panel3, 200, 240);
    lv_obj_align(ui_Panel3, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel3, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
 
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_scrollbar_mode(ui_Panel3, LV_SCROLLBAR_MODE_OFF);
 
    ui_LabelTitle3 = lv_label_create(ui_Panel3);
    lv_obj_set_style_text_font(ui_LabelTitle3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelTitle3, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_LabelTitle3, "SysCom");
    lv_obj_align(ui_LabelTitle3, LV_ALIGN_TOP_MID, 0, 10);
    
    create_menu_button(ui_Panel3, "MAVLink", mavlink_btn_click_cb, lv_color_hex(0xffffff), 35);
    create_menu_button(ui_Panel3, "Battery", battery_btn_click_cb, lv_color_hex(0xffff00), 80);
    create_menu_button(ui_Panel3, "System", system_btn_click_cb, lv_color_hex(0x00ffff), 125);
    
    // --- GPS Toggle Button (before Reboot) ---
    ui_Screen3_ToggleBtn = lv_btn_create(ui_Panel3);
    lv_obj_set_size(ui_Screen3_ToggleBtn, 180, 40);
    lv_obj_align(ui_Screen3_ToggleBtn, LV_ALIGN_TOP_LEFT, 5, 170);
    lv_obj_set_style_bg_color(ui_Screen3_ToggleBtn, lv_color_hex(0x0080FF), LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Screen3_ToggleBtn, ui_Screen3_toggle_cb, LV_EVENT_CLICKED, NULL);

    lv_obj_t *btn_label = lv_label_create(ui_Screen3_ToggleBtn);
    lv_label_set_text(btn_label, "GPS");
    lv_obj_set_style_text_color(btn_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(btn_label, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_center(btn_label);
    
    // Create reboot button (will be shown/hidden based on autopilot type)
    ui_RebootButton = create_menu_button(ui_Panel3, "Reboot", reboot_btn_click_cb, lv_color_hex(0xff0000), 215);
    
    // Initially hide reboot button, show after heartbeat determines autopilot type
    if (mavlink_data.autopilot_type != 3) {
        lv_obj_add_flag(ui_RebootButton, LV_OBJ_FLAG_HIDDEN);
    }
    
    // --- GPS Sub-screen Panel (hidden by default) ---
    ui_Screen3_GPS_Panel = lv_obj_create(ui_Screen3);
    lv_obj_set_size(ui_Screen3_GPS_Panel, 200, 180);
    lv_obj_align(ui_Screen3_GPS_Panel, LV_ALIGN_CENTER, 0, -10);
    lv_obj_set_style_bg_color(ui_Screen3_GPS_Panel, lv_color_hex(0x1a1a1a), LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Screen3_GPS_Panel, 0, LV_PART_MAIN);
    lv_obj_add_flag(ui_Screen3_GPS_Panel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_Screen3_GPS_Panel, LV_OBJ_FLAG_SCROLLABLE);

    // GPS Title
    lv_obj_t *gps_title = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(gps_title, "GPS Info");
    lv_obj_set_style_text_color(gps_title, lv_color_hex(0x00FF00), LV_PART_MAIN);
    lv_obj_set_style_text_font(gps_title, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(gps_title, LV_ALIGN_TOP_MID, 0, 5);

    // Latitude label
    ui_Screen3_GPS_Lat = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(ui_Screen3_GPS_Lat, "Lat: --.------");
    lv_obj_set_style_text_color(ui_Screen3_GPS_Lat, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Screen3_GPS_Lat, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(ui_Screen3_GPS_Lat, LV_ALIGN_TOP_LEFT, 10, 30);

    // Longitude label
    ui_Screen3_GPS_Lon = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(ui_Screen3_GPS_Lon, "Lon: --.------");
    lv_obj_set_style_text_color(ui_Screen3_GPS_Lon, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Screen3_GPS_Lon, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(ui_Screen3_GPS_Lon, LV_ALIGN_TOP_LEFT, 10, 50);

    // Altitude label
    ui_Screen3_GPS_Alt = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(ui_Screen3_GPS_Alt, "Alt: --- m");
    lv_obj_set_style_text_color(ui_Screen3_GPS_Alt, lv_color_hex(0xFFFFFF), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Screen3_GPS_Alt, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(ui_Screen3_GPS_Alt, LV_ALIGN_TOP_LEFT, 10, 70);

    // Satellites label
    ui_Screen3_GPS_Sats = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(ui_Screen3_GPS_Sats, "Sats: --");
    lv_obj_set_style_text_color(ui_Screen3_GPS_Sats, lv_color_hex(0xFFFF00), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Screen3_GPS_Sats, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(ui_Screen3_GPS_Sats, LV_ALIGN_TOP_LEFT, 10, 95);

    // Fix type label
    ui_Screen3_GPS_Fix = lv_label_create(ui_Screen3_GPS_Panel);
    lv_label_set_text(ui_Screen3_GPS_Fix, "Fix: No GPS");
    lv_obj_set_style_text_color(ui_Screen3_GPS_Fix, lv_color_hex(0xFF0000), LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Screen3_GPS_Fix, &lv_font_montserrat_14, LV_PART_MAIN);
    lv_obj_align(ui_Screen3_GPS_Fix, LV_ALIGN_TOP_LEFT, 10, 115);

    // Make GPS panel clickable to close it
    lv_obj_add_flag(ui_Screen3_GPS_Panel, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(ui_Screen3_GPS_Panel, ui_Screen3_gps_panel_click_cb, LV_EVENT_CLICKED, NULL);
    
    // Add swipe gesture support for circular navigation
    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);
    ui_enable_event_bubble_recursive(ui_Screen3);
    ui_Screen3_load_time = lv_tick_get();
}

// Helper: add event bubble to all children
static void ui_enable_event_bubble_recursive(lv_obj_t *parent) {
    uint32_t child_count = lv_obj_get_child_cnt(parent);
    for (uint32_t i = 0; i < child_count; i++) {
        lv_obj_t *child = lv_obj_get_child(parent, i);
        lv_obj_add_flag(child, LV_OBJ_FLAG_EVENT_BUBBLE);
        ui_enable_event_bubble_recursive(child);
    }
}

// Swipe event handler using PRESSED/RELEASED
static void ui_event_Screen3(lv_event_t *e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_get_act();
    lv_point_t point;
    if (!indev) return;
    if ((lv_tick_get() - ui_Screen3_load_time) < 400) return;
    if (event_code == LV_EVENT_PRESSED) {
        lv_indev_get_point(indev, &ui_Screen3_press_point);
        ui_Screen3_press_active = true;
    }
    if (event_code == LV_EVENT_PRESS_LOST) {
        ui_Screen3_press_active = false;
    }
    if (event_code == LV_EVENT_RELEASED && ui_Screen3_press_active) {
        int dx, dy;
        ui_Screen3_press_active = false;
        lv_indev_get_point(indev, &point);
        dx = point.x - ui_Screen3_press_point.x;
        dy = point.y - ui_Screen3_press_point.y;
        if (LV_ABS(dy) > 40 && LV_ABS(dy) > LV_ABS(dx)) {
            if (dy > 0) {
                _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 300, 0, &ui_Screen4_screen_init);
            } else {
                _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_Screen2_screen_init);
            }
        }
    }
}

void update_reboot_button_visibility(void) {
    if (!ui_RebootButton) return;
    if (mavlink_data.autopilot_type == 3) {
        lv_obj_clear_flag(ui_RebootButton, LV_OBJ_FLAG_HIDDEN);
    } else {
        lv_obj_add_flag(ui_RebootButton, LV_OBJ_FLAG_HIDDEN);
    }
}

void ui_Screen3_screen_destroy(void) {
    // Objects are automatically destroyed by LVGL when screen is deleted
}
