// This file was generated by SquareLine Studio
// Refactored for clean modal buttons

#include "ui_Screen3.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t *ui_Screen3;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_LabelTitle3;

///////////////////// FORWARD DECLARATIONS ////////////////////
static void modal_close_cb(lv_event_t *e);
static lv_obj_t* create_detail_modal(const char *title, const char *content);
static lv_obj_t* create_menu_button(lv_obj_t *parent, const char *label_text, lv_event_cb_t click_cb, lv_color_t text_color, lv_coord_t y_pos);
static void mavlink_btn_click_cb(lv_event_t *e);
static void serial_btn_click_cb(lv_event_t *e);
static void battery_btn_click_cb(lv_event_t *e);
static void system_btn_click_cb(lv_event_t *e);

///////////////////// MODAL FUNCTIONS ////////////////////

static void modal_close_cb(lv_event_t *e) {
    lv_obj_t *modal = lv_event_get_current_target(e);
    lv_obj_del(modal);
}

static lv_obj_t* create_detail_modal(const char *title, const char *content) {
    lv_obj_t *modal = lv_obj_create(lv_scr_act());
    lv_obj_set_size(modal, 200, 180);
    lv_obj_center(modal);
    lv_obj_set_style_bg_color(modal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(modal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(modal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(modal, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_t *title_label = lv_label_create(modal);
    lv_obj_set_style_text_font(title_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(title_label, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(title_label, title);
    lv_obj_align(title_label, LV_ALIGN_TOP_MID, 0, 10);
    
    lv_obj_t *content_label = lv_label_create(modal);
    lv_obj_set_style_text_font(content_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(content_label, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(content_label, content);
    lv_obj_align(content_label, LV_ALIGN_TOP_LEFT, 10, 35);
    lv_label_set_long_mode(content_label, LV_LABEL_LONG_WRAP);
    lv_obj_set_width(content_label, 180);
    
    lv_obj_add_flag(modal, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(modal, modal_close_cb, LV_EVENT_CLICKED, NULL);
    
    lv_obj_clear_flag(title_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(content_label, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(title_label, LV_OBJ_FLAG_EVENT_BUBBLE);
    lv_obj_add_flag(content_label, LV_OBJ_FLAG_EVENT_BUBBLE);
    
    return modal;
}

///////////////////// BUTTON HANDLERS ////////////////////

static void mavlink_btn_click_cb(lv_event_t *e) {
    (void)e;
    create_detail_modal("MAVLink Details",
        "MAVLink: Connected\n"
        "Messages: 42\n"
        "Last: Battery Status\n"
        "System ID: 1\n"
        "Component: 1\n"
        "Heartbeat: OK\n"
        "GPS: Connected");
}

static void serial_btn_click_cb(lv_event_t *e) {
    (void)e;
    create_detail_modal("MAVLink Wiring",
        "Flight Controller → Xiao:\n"
        "TX → D3 (GPIO3) RX\n"
        "RX → D5 (GPIO5) TX\n"
        "GND → GND\n"
        "\n"
        "Baud: 57600\n"
        "UART: Serial1");
}

static void battery_btn_click_cb(lv_event_t *e) {
    (void)e;
    create_detail_modal("Battery Details",
        "Battery: 85%\n"
        "Voltage: 12.6V\n"
        "Current: 2.1A\n"
        "Remaining: 51 min\n"
        "Temperature: 25C\n"
        "Cells: 6S");
}

static void system_btn_click_cb(lv_event_t *e) {
    (void)e;
    create_detail_modal("System Status",
        "Status: Active\n"
        "Uptime: 1234s\n"
        "Memory: 80KB\n"
        "WiFi: Connected\n"
        "Signal: -45dBm\n"
        "Free Space: 2MB");
}

///////////////////// BUTTON CREATOR ////////////////////

static lv_obj_t* create_menu_button(lv_obj_t *parent, const char *label_text, lv_event_cb_t click_cb, lv_color_t text_color, lv_coord_t y_pos) {
    lv_obj_t *btn = lv_btn_create(parent);
    lv_obj_set_size(btn, 180, 40);
    lv_obj_align(btn, LV_ALIGN_TOP_LEFT, 5, y_pos);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x2a2a2a), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(btn, lv_color_hex(0x3a3a3a), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_radius(btn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(btn, click_cb, LV_EVENT_CLICKED, NULL);
    
    lv_obj_t *label = lv_label_create(btn);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(label, text_color, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(label, label_text);
    lv_obj_center(label);
    
    return btn;
}

///////////////////// SCREEN INITIALIZATION ////////////////////

void ui_Screen3_screen_init(void) {
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Screen3, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Screen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Screen3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Create main panel - transparent background
    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_size(ui_Panel3, 200, 240);
    lv_obj_align(ui_Panel3, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Panel3, 110, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_Panel3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    lv_obj_set_scrollbar_mode(ui_Panel3, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_scroll_dir(ui_Panel3, LV_DIR_VER);
    
    ui_LabelTitle3 = lv_label_create(ui_Panel3);
    lv_obj_set_style_text_font(ui_LabelTitle3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_LabelTitle3, lv_color_hex(0x00ff00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_label_set_text(ui_LabelTitle3, "SysCom");
    lv_obj_align(ui_LabelTitle3, LV_ALIGN_TOP_MID, 0, 10);
    
    create_menu_button(ui_Panel3, "MAVLink", mavlink_btn_click_cb, lv_color_hex(0xffffff), 35);
    create_menu_button(ui_Panel3, "Serial", serial_btn_click_cb, lv_color_hex(0xaaaaaa), 80);
    create_menu_button(ui_Panel3, "Battery", battery_btn_click_cb, lv_color_hex(0xffff00), 125);
    create_menu_button(ui_Panel3, "System", system_btn_click_cb, lv_color_hex(0x00ffff), 170);
}

void ui_Screen3_screen_destroy(void) {
    // Objects are automatically destroyed by LVGL when screen is deleted
}
